# Generated by Django 4.0.4 on 2022-08-03 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_office_user_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='office',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='tel',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
