from django.urls import path
from books import views 
app_name = 'books'

urlpatterns = [
     path("bnc/", views.BnCView.as_view(), name="bnc"),
     path("room-lease/", views.RoomLeaseList.as_view(), name="room-lease-list"),
     path("room-lease/<int:pk>/", views.RoomLeaseDetail.as_view(),
          name="room-lease-detail"),
     path("room-lease/<int:pk>/update/",
          views.RoomLeaseUpdate.as_view(), name="room-lease-update"),
     path("room-lease/<int:pk>/delete/",
          views.roomlease_delete, name="room-lease-delete"),
     path("room-lease/search/", views.roomlease_search, name="room-lease-search"),
     path("room-lease/creating/", views.RoomLeaseCreating.as_view(),
          name="room-lease-creating"),

     path("apartment-lease/", views.ApartmentLeaseList.as_view(), name="apartment-lease-list"),
     path("apartment-lease/<int:pk>/", views.ApartmentLeaseDetail.as_view(),
          name="apartment-lease-detail"),
     path("apartment-lease/<int:pk>/update/",
          views.ApartmentLeaseUpdate.as_view(), name="apartment-lease-update"),
     path("apartment-lease/<int:pk>/delete/",
          views.apartmentlease_delete, name="apartment-lease-delete"),
     path("apartment-lease/search/", views.apartmentlease_search, name="apartment-lease-search"),
     path("apartment-lease/creating/", views.ApartmentLeaseCreating.as_view(),
          name="apartment-lease-creating"),

     path("officetel-lease/", views.OfficetelLeaseList.as_view(), name="officetel-lease-list"),
     path("officetel-lease/<int:pk>/", views.OfficetelLeaseDetail.as_view(),
          name="officetel-lease-detail"),
     path("officetel-lease/<int:pk>/update/",
          views.OfficetelLeaseUpdate.as_view(), name="officetel-lease-update"),
     path("officetel-lease/<int:pk>/delete/",
          views.officetellease_delete, name="officetel-lease-delete"),
     path("officetel-lease/search/", views.officetellease_search, name="officetel-lease-search"),
     path("officetel-lease/creating/", views.OfficetelLeaseCreating.as_view(),
          name="officetel-lease-creating"),

     path("room-dealing/", views.RoomDealingList.as_view(), name="room-dealing-list"),
     path("room-dealing/<int:pk>/", views.RoomDealingDetail.as_view(),
          name="room-dealing-detail"),
     path("room-dealing/<int:pk>/update/",
          views.RoomDealingUpdate.as_view(), name="room-dealing-update"),
     path("room-dealing/<int:pk>/delete/",
          views.roomdealing_delete, name="room-dealing-delete"),
     path("room-dealing/search/", views.roomdealing_search, name="room-dealing-search"),
     path("room-dealing/creating/", views.RoomDealingCreating.as_view(),
          name="room-dealing-creating"),
     
     path("apartment-dealing/", views.ApartmentDealingList.as_view(), name="apartment-dealing-list"),
     path("apartment-dealing/<int:pk>/", views.ApartmentDealingDetail.as_view(),
          name="apartment-dealing-detail"),
     path("apartment-dealing/<int:pk>/update/",
          views.ApartmentDealingUpdate.as_view(), name="apartment-dealing-update"),
     path("apartment-dealing/<int:pk>/delete/",
          views.apartmentdealing_delete, name="apartment-dealing-delete"),
     path("apartment-dealing/search/", views.apartmentdealing_search, name="apartment-dealing-search"),
     path("apartment-dealing/creating/", views.ApartmentDealingCreating.as_view(),
          name="apartment-dealing-creating"),

     path("officetel-dealing/", views.OfficetelDealingList.as_view(), name="officetel-dealing-list"),
     path("officetel-dealing/<int:pk>/", views.OfficetelDealingDetail.as_view(),
          name="officetel-dealing-detail"),
     path("officetel-dealing/<int:pk>/update/",
          views.OfficetelDealingUpdate.as_view(), name="officetel-dealing-update"),
     path("officetel-dealing/<int:pk>/delete/",
          views.officeteldealing_delete, name="officetel-dealing-delete"),
     path("officetel-dealing/search/", views.officeteldealing_search, name="officetel-dealing-search"),
     path("officetel-dealing/creating/", views.OfficetelDealingCreating.as_view(),
          name="officetel-dealing-creating"),

          path("store-dealing/", views.StoreDealingList.as_view(), name="store-dealing-list"),
     path("store-dealing/<int:pk>/", views.StoreDealingDetail.as_view(),
          name="store-dealing-detail"),
     path("store-dealing/<int:pk>/update/",
          views.StoreDealingUpdate.as_view(), name="store-dealing-update"),
     path("store-dealing/<int:pk>/delete/",
          views.storedealing_delete, name="store-dealing-delete"),
     path("store-dealing/search/", views.storedealing_search, name="store-dealing-search"),
     path("store-dealing/creating/", views.StoreDealingCreating.as_view(),
          name="store-dealing-creating"),

     path("store-lease/", views.StoreLeaseList.as_view(), name="store-lease-list"),
     path("store-lease/<int:pk>/", views.StoreLeaseDetail.as_view(),
          name="store-lease-detail"),
     path("store-lease/creating/", views.StoreLeaseCreating.as_view(),
          name="store-lease-creating"),
     path("store-lease/<int:pk>/update/",
          views.StoreLeaseUpdate.as_view(), name="store-lease-update"),
     path("store-lease/search/", views.storelease_search, name="store-lease-search"),
     path("store-lease/<int:pk>/delete/",
          views.storelease_delete, name="store-lease-delete"),
     path("building-dealing/", views.BuildingDealingList.as_view(),
          name="building-dealing-list"),
     path("building-dealing/<int:pk>/", views.BuildingDealingDetail.as_view(),
          name="building-dealing-detail"),
     path("building-dealing/<int:pk>/update/",
          views.BuildingDealingUpdate.as_view(), name="building-dealing-update"),
     path("building-dealing/<int:pk>/delete/",
          views.buildingdealing_delete, name="building-dealing-delete"),
     path("building-dealing/search/", views.buildingdealing_search,
          name="building-dealing-search"),
     path("building-dealing/creating/", views.BuildingDealingCreating.as_view(),
          name="building-dealing-creating"),
]
