# Generated by Django 4.0.4 on 2022-06-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_apartmentdealing_dabang_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomdealing',
            name='area_m2',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='roomdealing',
            name='dabang',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='roomdealing',
            name='deposit',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='roomdealing',
            name='elevator',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='roomdealing',
            name='empty',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='roomdealing',
            name='loan',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='roomdealing',
            name='month_fee',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='roomdealing',
            name='naver',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='roomdealing',
            name='not_finished',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='roomdealing',
            name='parking',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='roomdealing',
            name='peterpan',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='roomdealing',
            name='zicbang',
            field=models.BooleanField(null=True),
        ),
    ]
