# Generated by Django 4.0.4 on 2022-08-02 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_officeteldealing_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentlease',
            name='land_m2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='officetellease',
            name='land_m2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roomlease',
            name='land_m2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storelease',
            name='land_m2',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
