# Generated by Django 4.0.4 on 2022-06-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_roomdealing_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomdealing',
            name='peterpan',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
