# Generated by Django 4.0.4 on 2022-08-02 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_apartmentlease_land_m2_officetellease_land_m2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingdealing',
            name='bath',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buildingdealing',
            name='room',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
