# Generated by Django 4.0.4 on 2022-06-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_roomdealing_peterpan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomdealing',
            name='area_m2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='roomdealing',
            name='dabang',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roomdealing',
            name='deposit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='roomdealing',
            name='elevator',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roomdealing',
            name='empty',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roomdealing',
            name='loan',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roomdealing',
            name='month_fee',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='roomdealing',
            name='naver',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roomdealing',
            name='not_finished',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='roomdealing',
            name='parking',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roomdealing',
            name='zicbang',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
