# Generated by Django 4.0.4 on 2022-06-01 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0008_alter_roomdealing_area_m2_alter_roomdealing_dabang_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomdealing',
            name='realtor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
