# Generated by Django 4.0.4 on 2022-08-02 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_buildingdealing_bath_buildingdealing_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingdealing',
            name='land_type',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
