# Generated by Django 4.0.4 on 2022-06-06 03:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_alter_roomdealing_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomdealing',
            name='updated',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 6, 6, 3, 57, 26, 667695, tzinfo=utc), null=True),
        ),
    ]
