# Generated by Django 4.0.4 on 2022-06-18 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_alter_roomdealing_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomdealing',
            name='updated',
            field=models.DateField(blank=True, default='2022-06-18', null=True),
        ),
    ]
