# Generated by Django 4.0.4 on 2022-06-26 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0025_alter_officeteldealing_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedealing',
            name='deposit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storedealing',
            name='month_fee',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
