# Generated by Django 4.0.4 on 2022-07-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0034_alter_officeteldealing_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentdealing',
            name='deposit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apartmentdealing',
            name='month_fee',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
