# Generated by Django 4.0.4 on 2022-07-04 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0036_alter_apartmentdealing_deposit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentdealing',
            name='deposit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apartmentdealing',
            name='month_fee',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
