# Generated by Django 4.0.4 on 2022-07-15 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('managements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='management',
            name='realtor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managements', to=settings.AUTH_USER_MODEL),
        ),
    ]
