# Generated by Django 4.0.4 on 2022-07-03 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='management',
            old_name='manager',
            new_name='realtor',
        ),
    ]
