# Generated by Django 4.1.5 on 2023-03-19 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentDealingCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_phone', models.CharField(max_length=100)),
                ('updated', models.DateField(blank=True, null=True)),
                ('parking', models.BooleanField()),
                ('elevator', models.BooleanField()),
                ('loan', models.BooleanField()),
                ('not_finished', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('area_m2', models.FloatField()),
                ('price', models.IntegerField()),
                ('room', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ApartmentLeaseCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_phone', models.CharField(max_length=100)),
                ('updated', models.DateField(blank=True, null=True)),
                ('room', models.IntegerField()),
                ('deposit', models.IntegerField()),
                ('month_fee', models.IntegerField()),
                ('area_m2', models.FloatField()),
                ('parking', models.BooleanField()),
                ('elevator', models.BooleanField()),
                ('loan', models.BooleanField()),
                ('not_finished', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BuildingDealingCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_phone', models.CharField(max_length=100)),
                ('updated', models.DateField(blank=True, null=True)),
                ('price', models.IntegerField()),
                ('land_m2', models.FloatField(blank=True, null=True)),
                ('elevator', models.BooleanField()),
                ('loan', models.BooleanField()),
                ('not_finished', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HouseDealingCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_phone', models.CharField(max_length=100)),
                ('updated', models.DateField(blank=True, null=True)),
                ('room', models.IntegerField()),
                ('price', models.IntegerField()),
                ('area_m2', models.FloatField()),
                ('parking', models.BooleanField()),
                ('elevator', models.BooleanField()),
                ('loan', models.BooleanField()),
                ('not_finished', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HouseLeaseCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_phone', models.CharField(max_length=100)),
                ('updated', models.DateField(blank=True, null=True)),
                ('room', models.IntegerField()),
                ('deposit', models.IntegerField()),
                ('month_fee', models.IntegerField()),
                ('area_m2', models.FloatField()),
                ('parking', models.BooleanField()),
                ('elevator', models.BooleanField()),
                ('loan', models.BooleanField()),
                ('not_finished', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OfficetelDealingCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_phone', models.CharField(max_length=100)),
                ('updated', models.DateField(blank=True, null=True)),
                ('room', models.IntegerField()),
                ('price', models.IntegerField()),
                ('area_m2', models.FloatField()),
                ('parking', models.BooleanField()),
                ('elevator', models.BooleanField()),
                ('loan', models.BooleanField()),
                ('not_finished', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OfficetelLeaseCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_phone', models.CharField(max_length=100)),
                ('updated', models.DateField(blank=True, null=True)),
                ('room', models.IntegerField()),
                ('deposit', models.IntegerField()),
                ('month_fee', models.IntegerField()),
                ('area_m2', models.FloatField()),
                ('parking', models.BooleanField()),
                ('elevator', models.BooleanField()),
                ('loan', models.BooleanField()),
                ('not_finished', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShopDealingCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_phone', models.CharField(max_length=100)),
                ('updated', models.DateField(blank=True, null=True)),
                ('price', models.IntegerField()),
                ('area_m2', models.FloatField()),
                ('parking', models.BooleanField()),
                ('elevator', models.BooleanField()),
                ('loan', models.BooleanField()),
                ('not_finished', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShopLeaseCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_phone', models.CharField(max_length=100)),
                ('updated', models.DateField(blank=True, null=True)),
                ('deposit', models.IntegerField()),
                ('month_fee', models.IntegerField()),
                ('area_m2', models.FloatField()),
                ('parking', models.BooleanField()),
                ('loan', models.BooleanField()),
                ('elevator', models.BooleanField()),
                ('not_finished', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
