# Generated by Django 4.0.4 on 2022-07-01 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildingdealingcustomer',
            name='parking',
        ),
    ]
