# Generated by Django 4.0.4 on 2022-08-02 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('home_id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
